// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddToWatchlist(arg1:string):Promise<Array<main.WatchItem>>;

export function DiagnoseBi(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.BiDiagnosis>;

export function GetKline(arg1:string,arg2:string,arg3:number):Promise<main.KlineWithChan>;

export function GetStatus():Promise<main.Status>;

export function GetStockInfo(arg1:string):Promise<main.StockInfo>;

export function GetWatchlist():Promise<Array<main.WatchItem>>;

export function RemoveFromWatchlist(arg1:string):Promise<Array<main.WatchItem>>;

export function ReorderWatchlist(arg1:Array<string>):Promise<Array<main.WatchItem>>;
