// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToWatchlist(arg1) {
  return window['go']['main']['App']['AddToWatchlist'](arg1);
}

export function DiagnoseBi(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DiagnoseBi'](arg1, arg2, arg3, arg4);
}

export function DiagnoseSegment(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['DiagnoseSegment'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetKline(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetKline'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetStockInfo(arg1) {
  return window['go']['main']['App']['GetStockInfo'](arg1);
}

export function GetWatchlist() {
  return window['go']['main']['App']['GetWatchlist']();
}

export function RemoveFromWatchlist(arg1) {
  return window['go']['main']['App']['RemoveFromWatchlist'](arg1);
}

export function ReorderWatchlist(arg1) {
  return window['go']['main']['App']['ReorderWatchlist'](arg1);
}

export function SetTdxDir(arg1) {
  return window['go']['main']['App']['SetTdxDir'](arg1);
}
